version: "3"
services:
  mysqldb:
    image: mysql:5.7
    container_name: ${DB_CONTAINER:-mysql}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - MYSQL_USER=${DB_USERNAME:-yourusername}
      - MYSQL_PASSWORD=${DB_PASSWORD:-yoursecret}
      - MYSQL_DATABASE=${DB_DATABASE:-yourdatabase}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
  api_service:
    build: .
    container_name: ${API_CONTAINER:-api-booking}
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true